### ISSUE TITLE
Kotlin Native build cache not working witch Clikt

### ISSUE THREAD

**Issue by Jeansen** [ajalt/clikt#598]
I cannot build t without setting `kotlin.native.cacheKind.linuxX64=none`. Otherwise I get errors like the following:

e: /home/marcel/.konan/dependencies/llvm-16.0.0-x86_64-linux-essentials-80/bin/ld.lld invocation reported errors
Please try to disable compiler caches and rerun the build. To disable compiler caches, add the following line to the gradle.properties file in the project's root directory:
    
    kotlin.native.cacheKind.linuxX64=none

```    
Also, consider filing an issue with full Gradle log here: https://kotl.in/issue
The /home/marcel/.konan/dependencies/llvm-16.0.0-x86_64-linux-essentials-80/bin/ld.lld command returned non-zero exit code: 1.
output:
ld.lld: error: duplicate symbol: kfun:com.github.ajalt.clikt.core#selfAndAncestors__at__com.github.ajalt.clikt.core.Context(){}kotlin.sequences.Sequence<com.github.ajalt.clikt.core.Context>
>>> defined at Context.kt:0 (/home/runner/work/clikt/clikt/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/core/Context.kt:0)
>>>            libclikt:clikt-cache.a.o:(kfun:com.github.ajalt.clikt.core#selfAndAncestors__at__com.github.ajalt.clikt.core.Context(){}kotlin.sequences.Sequence<com.github.ajalt.clikt.core.Context>) in archive /home/marcel/.konan/kotlin-native-prebuilt-linux-x86_64-2.1.21/klib/cache/linux_x64-gSTATIC-pl/clikt:clikt/2kl1yhs57l8hi.27dt4c2kmz6t1/clikt:clikt-cache/bin/libclikt:clikt-cache.a
>>> defined at MordantContext.kt:0 (/home/runner/work/clikt/clikt/clikt-mordant/src/commonMain/kotlin/com/github/ajalt/clikt/core/MordantContext.kt:0)
>>>            libclikt:clikt-mordant-cache.a.o:(.text.kfun:com.github.ajalt.clikt.core#selfAndAncestors__at__com.github.ajalt.clikt.core.Context(){}kotlin.sequences.Sequence<com.github.ajalt.clikt.core.Context>+0x0) in archive /home/marcel/.konan/kotlin-native-prebuilt-linux-x86_64-2.1.21/klib/cache/linux_x64-gSTATIC-pl/clikt:clikt-mordant/1t87yb9uusrck.2i5cj6zx0ov5n/clikt:clikt-mordant-cache/bin/libclikt:clikt-mordant-cache.a

```

So I wonder, if there is anything additional/special I have to set in the build configuration with Gradle? The above directive makes re-compiling ultra slow ;-(

**Comment by sirekanian** [comment]
I just want to start with KMP and Clikt, but recompiling takes so long... Is it problem with only one function? Could you please rename it? 🥺 As I see it is `internal` :)

**Comment by sirekanian** [comment]
I've found a workaround that works for me, I just using `clikt-core` instead of `clikt`:
```
commonMainImplementation("com.github.ajalt.clikt:clikt-core:5.0.3")
```
And changed `CliktCommand` to `CoreCliktCommand` in my code. Hope it helps to someone.

**Comment by Jeansen** [comment]
Oh, great! That works for me, too. At least for the debug builds. Release Builds take a lot longer, but that is expected since they are heavily optimized. But be aware, that you miss-out some functionalities with this, should you need them https://ajalt.github.io/clikt/advanced/#core-module .

**Comment by Jeansen** [comment]
@gfreitash: Awsome! Works like a charm, even with other dependencies I have, like custom build Kubernetes lib, SSL etc ... Cannot find any issues, so far :-) Thanks for sharing your find!

**Comment by jj-sn** [comment]
I get the same error **even without caching** (with `kotlin.native.cacheKind.linuxX64=none` added to `gradle.properties`). This is the case with Kotlin 2.3.20 and 2.3.21, but it works fine with Kotlin 2.3.10.

I found another related Kotlin issue: https://youtrack.jetbrains.com/issue/KT-75928/ld.lld-error-duplicate-symbol-when-enabling-.konan-cache

UPDATE: Compilation actually works with the cache disabled. I simply forgot to use the new [cache control DSL](https://kotlinlang.org/docs/whatsnew2320.html#new-dsl-for-disabling-compilation-cache).

**Comment by Jadarma** [comment]
> I get the same error **even without caching** (with `kotlin.native.cacheKind.linuxX64=none` added to `gradle.properties`). This is the case with Kotlin 2.3.20 and 2.3.21, but it works fine with Kotlin 2.3.10.

@jj-sn That's because Kotlin 2.3.20 introduced a [Gradle DSL for disabling native caches](https://kotlinlang.org/docs/whatsnew2320.html#new-dsl-for-disabling-compilation-cache), and the `gradle.properties` are no longer used. So if you don't use the new DSL, you actually run with the caches enabled after all.

If I'm not mistaken there should be a warning in the logs about using the deprecated properties somewhere. This was the case for me when I updated to 2.3.20.

**Comment by Hansanto** [comment]
With the [new Gradle DSL](https://kotlinlang.org/docs/whatsnew2320.html#new-dsl-for-disabling-compilation-cache):
```kt
kotlin.targets.withType<KotlinNativeTarget> {
        binaries {
            executable {
                // ...

                disableNativeCache(
                    version = DisableCacheInKotlinVersion.`2_3_21`,
                    reason = "Clikt has duplicate symbol",
                    issueUrl = URI("https://github.com/ajalt/clikt/issues/598")
                )
            }
        }
    }
```

**Comment by jj-sn** [comment]
> [@jj-sn](https://github.com/jj-sn) That's because Kotlin 2.3.20 introduced a [Gradle DSL for disabling native caches](https://kotlinlang.org/docs/whatsnew2320.html#new-dsl-for-disabling-compilation-cache), and the `gradle.properties` are no longer used. So if you don't use the new DSL, you actually run with the caches enabled after all.

@Hansanto You're right! Sorry for the noise.
